export interface ExerciseSeed {
  id: number;
  name: string;
  category: "strength" | "cardio" | "mobility" | "core";
  muscle_group: string;
  equipment: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  instructions: string;
  video_search_query: string;
}

// A starter library covering the major movement patterns. Each exercise links
// out to a YouTube search (rather than a hardcoded video id) so the link never
// rots or points at the wrong clip — the user picks whichever reputable
// demonstration they prefer from the results.
export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  { id: 1, name: "Barbell Back Squat", category: "strength", muscle_group: "legs", equipment: "barbell, rack", difficulty: "intermediate", instructions: "Bar on upper traps, feet shoulder-width. Break at hips and knees together, chest up, descend until thighs are at least parallel, drive through mid-foot to stand.", video_search_query: "how to barbell back squat proper form" },
  { id: 2, name: "Goblet Squat", category: "strength", muscle_group: "legs", equipment: "dumbbell or kettlebell", difficulty: "beginner", instructions: "Hold a dumbbell vertically at chest. Squat down keeping torso upright and elbows brushing inside knees, drive back up.", video_search_query: "goblet squat proper form tutorial" },
  { id: 3, name: "Romanian Deadlift", category: "strength", muscle_group: "hamstrings/glutes", equipment: "barbell or dumbbells", difficulty: "intermediate", instructions: "Slight knee bend, hinge at hips pushing them back, keep bar close to legs, lower until hamstring stretch, drive hips forward to stand.", video_search_query: "romanian deadlift proper form tutorial" },
  { id: 4, name: "Conventional Deadlift", category: "strength", muscle_group: "full body/posterior chain", equipment: "barbell", difficulty: "advanced", instructions: "Bar over mid-foot, grip just outside legs, flat back, chest up. Drive through the floor, hips and shoulders rise together, lock out standing tall.", video_search_query: "conventional deadlift proper form tutorial" },
  { id: 5, name: "Walking Lunge", category: "strength", muscle_group: "legs", equipment: "bodyweight or dumbbells", difficulty: "beginner", instructions: "Step forward, lower back knee toward floor keeping front shin vertical, push through front heel to step into the next lunge.", video_search_query: "walking lunge proper form" },
  { id: 6, name: "Bulgarian Split Squat", category: "strength", muscle_group: "legs", equipment: "bench, dumbbells optional", difficulty: "intermediate", instructions: "Rear foot elevated on a bench. Lower straight down until front thigh is parallel, drive through front heel.", video_search_query: "bulgarian split squat proper form" },
  { id: 7, name: "Hip Thrust", category: "strength", muscle_group: "glutes", equipment: "bench, barbell optional", difficulty: "beginner", instructions: "Upper back on a bench, bar or bodyweight at hips. Drive hips up to full extension, squeeze glutes at top, lower under control.", video_search_query: "barbell hip thrust proper form" },
  { id: 8, name: "Push-Up", category: "strength", muscle_group: "chest/triceps/shoulders", equipment: "bodyweight", difficulty: "beginner", instructions: "Hands under shoulders, body in a straight line. Lower chest to just above the floor keeping elbows ~45°, press back up.", video_search_query: "push up proper form tutorial" },
  { id: 9, name: "Bench Press", category: "strength", muscle_group: "chest/triceps/shoulders", equipment: "barbell, bench", difficulty: "intermediate", instructions: "Grip slightly wider than shoulders, retract shoulder blades, lower bar to mid-chest, press up without flaring elbows fully out.", video_search_query: "barbell bench press proper form" },
  { id: 10, name: "Dumbbell Shoulder Press", category: "strength", muscle_group: "shoulders", equipment: "dumbbells", difficulty: "beginner", instructions: "Dumbbells at shoulder height, press straight overhead without arching the lower back, lower under control.", video_search_query: "dumbbell shoulder press proper form" },
  { id: 11, name: "Pull-Up", category: "strength", muscle_group: "back/biceps", equipment: "pull-up bar", difficulty: "advanced", instructions: "Hang with an overhand grip, pull chin above the bar leading with the elbows, lower to a full hang under control.", video_search_query: "pull up proper form tutorial" },
  { id: 12, name: "Lat Pulldown", category: "strength", muscle_group: "back", equipment: "cable machine", difficulty: "beginner", instructions: "Grip bar wide, pull to upper chest driving elbows down and back, control the return without letting the weight stack slam.", video_search_query: "lat pulldown proper form" },
  { id: 13, name: "Bent-Over Row", category: "strength", muscle_group: "back", equipment: "barbell or dumbbells", difficulty: "intermediate", instructions: "Hinge to ~45°, flat back, pull weight to lower ribs squeezing shoulder blades together, lower with control.", video_search_query: "bent over row proper form" },
  { id: 14, name: "Plank", category: "core", muscle_group: "core", equipment: "bodyweight", difficulty: "beginner", instructions: "Forearms and toes on the floor, body in a straight line from head to heels, brace the core, avoid sagging hips.", video_search_query: "plank proper form tutorial" },
  { id: 15, name: "Dead Bug", category: "core", muscle_group: "core", equipment: "bodyweight", difficulty: "beginner", instructions: "Lie on back, arms up, knees at 90°. Lower opposite arm and leg toward the floor while keeping the low back pressed down, return and switch.", video_search_query: "dead bug exercise proper form" },
  { id: 16, name: "Hanging Knee Raise", category: "core", muscle_group: "core", equipment: "pull-up bar", difficulty: "intermediate", instructions: "Hang from a bar, raise knees toward chest using the abs (not momentum), lower under control.", video_search_query: "hanging knee raise proper form" },
  { id: 17, name: "Russian Twist", category: "core", muscle_group: "core/obliques", equipment: "bodyweight or weight plate", difficulty: "beginner", instructions: "Sit with knees bent, lean back slightly, rotate the torso side to side keeping the chest up.", video_search_query: "russian twist proper form" },
  { id: 18, name: "Kettlebell Swing", category: "cardio", muscle_group: "posterior chain/full body", equipment: "kettlebell", difficulty: "intermediate", instructions: "Hinge at the hips, snap them forward to swing the kettlebell to chest height using hip drive, not the arms.", video_search_query: "kettlebell swing proper form tutorial" },
  { id: 19, name: "Burpee", category: "cardio", muscle_group: "full body", equipment: "bodyweight", difficulty: "intermediate", instructions: "Drop to a squat, kick feet back to a plank, do a push-up, jump feet back in, and jump up explosively.", video_search_query: "burpee proper form tutorial" },
  { id: 20, name: "Mountain Climbers", category: "cardio", muscle_group: "core/full body", equipment: "bodyweight", difficulty: "beginner", instructions: "Start in a plank, drive knees alternately toward the chest at a fast pace while keeping the hips level.", video_search_query: "mountain climbers proper form" },
  { id: 21, name: "Jump Rope", category: "cardio", muscle_group: "full body/calves", equipment: "jump rope", difficulty: "beginner", instructions: "Small, quick wrist turns, light bounce on the balls of the feet, keep elbows close to the body.", video_search_query: "jump rope proper technique beginner" },
  { id: 22, name: "Rowing (Erg)", category: "cardio", muscle_group: "full body", equipment: "rowing machine", difficulty: "beginner", instructions: "Drive with the legs first, then lean back and pull the handle to the ribs, reverse the order on the return.", video_search_query: "rowing machine proper technique tutorial" },
  { id: 23, name: "Cat-Cow Stretch", category: "mobility", muscle_group: "spine", equipment: "bodyweight", difficulty: "beginner", instructions: "On hands and knees, alternate arching the spine up (cat) and dropping the belly with chest lifted (cow) with the breath.", video_search_query: "cat cow stretch proper form" },
  { id: 24, name: "World's Greatest Stretch", category: "mobility", muscle_group: "hips/thoracic spine", equipment: "bodyweight", difficulty: "beginner", instructions: "Lunge forward, drop the back knee, place the same-side hand down, rotate the opposite arm up toward the ceiling.", video_search_query: "world's greatest stretch tutorial" },
  { id: 25, name: "90/90 Hip Stretch", category: "mobility", muscle_group: "hips", equipment: "bodyweight", difficulty: "beginner", instructions: "Sit with front leg bent 90° in front, back leg bent 90° to the side, keep the chest tall and rotate between sides.", video_search_query: "90 90 hip stretch tutorial" },
  { id: 26, name: "Face Pull", category: "strength", muscle_group: "rear delts/upper back", equipment: "cable or band", difficulty: "beginner", instructions: "Pull a rope or band toward the face at eye height, leading with the elbows and rotating the hands outward at the end.", video_search_query: "face pull proper form" },
  { id: 27, name: "Farmer's Carry", category: "strength", muscle_group: "grip/core/full body", equipment: "dumbbells or kettlebells", difficulty: "beginner", instructions: "Hold a heavy weight in each hand, walk with a tall posture and braced core, avoid leaning to either side.", video_search_query: "farmers carry proper form" },
  { id: 28, name: "Standing Calf Raise", category: "strength", muscle_group: "calves", equipment: "bodyweight or dumbbells", difficulty: "beginner", instructions: "Rise onto the balls of the feet as high as possible, pause briefly, lower slowly past neutral for a full stretch.", video_search_query: "standing calf raise proper form" },
];
